### ISSUE TITLE
characteristic was supplied illegal value: number instead of string, supplying illegal values will throw errors in the future

### ISSUE THREAD

**Issue by amaedl** [larsxschneider/homebridge-secvest-kit#2]
Für jede Zone bekomme ich jeweils diese Fehlermeldung:

[10/07/2021, 16:42:11] [SecvestKit] Adding new accessory: MFS HWR
[MFS HWR@@Serial Number] characteristic was supplied illegal value: number instead of string, supplying illegal values will throw errors in the future

Alle Zonen haben bei mir Namen.

meine cfg:

{
            "host": "192.168.1.5",
            "port": 4433,
            "username": "yyyyyyy",
            "password": "xxx",
            "securityPartitions": [
                1
            ],
            "accessoryPartitions": [
                1
            ],
            "zoneTypes": {
                "207": "motion",
                "208": "motion",
                "209": "motion",
                "210": "motion"
            },
            "pollingInterval": 60,
            "pushover": {
                "notificationDelay": 15
            },
            "platform": "SecvestKit"
        }

**Comment by larsxschneider** [comment]
Hmm. Ich denke das Problem ist hier:
https://github.com/larsxschneider/homebridge-secvest-kit/blob/main/src/secvestMotionAccessory.ts#L21

Bei mir hat eine Errichterfirma das alles mal eingerichtet. Alle Zonen haben nichts sagende Nummern... ich dachte das geht nur so. Wie hast Du da da Namen reinbekommen?

Ich versuche das zeitnah zu fixen... aber die naechsten 4 Wochen wird es wahrscheinlich nichts.

**Comment by amaedl** [comment]
Yo - habe ich hier testweise behoben….
Wenn alles hier fertig ist, Machenschaften einen poll… 

-- 
Gruß

Andree


Sent via iPhone 11 Pro

**Comment by raphb83** [comment]
Ich habe leider dieselbe Fehlermeldung. Wie hast du @amaedl das denn teilweise behoben?

**Comment by JHPWBN** [comment]
Ich bin seit kurzem auch Benutzer von diesem tollen Plugin, es scheint alles richtig zu funktionieren, nichtsdestotrotz bekomme ich diese Fehlermeldung:

[9/21/2022, 12:14:31 PM] [homebridge-secvest-kit] This plugin generated a warning from the characteristic 'Serial Number': [Serial Number] characteristic must have a length of more than 1 character otherwise         HomeKit will reject this accessory, ignoring new value. See https://homebridge.io/w/JtMGR for more info.

Ich würde mich über eine Rückmeldung freuen.

Vielen Dank im Voraus!

**Comment by larsxschneider** [comment]
@JHPWBN Vielen Dank. Das ist nur eine Warning die Du ignorieren kannst - also aendert nichts an der Funktionalitaet. Ich mache keine Aenderungen mehr an dem Plugin weil ich jetzt von homebridge auf HomeAssistent gewechselt bin 😊

**Comment by JHPWBN** [comment]
OK Danke

**Comment by JHPWBN** [comment]
Hallo Lars, eine Frage hätte ich noch und zwar wie ich die Benachrichtigung raus kriege (pushover).
Habe schon versucht den Teil zu löschen aber dann geht nix mehr.

So sieht es bei mir aus:

"host": "192.168.xxx.xxx",

    "port": 4433,

    "username": "xxxx",

    "password": "xxx",

    "securityPartitions": [

        1

    ],

    "accessoryPartitions": [

        1

    ],

    "zoneTypes": {

        "202": "lock"

    },

    "pollingInterval": 2,

    "pushover": {

        "notificationDelay": 15,

        "ignoredZones": [

            1

        ]

    },

    "platform": "SecvestKit",

    "_bridge": {

        "username": "xxx",

        "port": xxx

    }


On 21. Sep 2022, at 13:00, Lars Schneider ***@***.***> wrote:


@JHPWBN <https://github.com/JHPWBN> Vielen Dank. Das ist nur eine Warning die Du ignorieren kannst - also aendert nichts an der Funktionalitaet. Ich mache keine Aenderungen mehr an dem Plugin weil ich jetzt von homebridge auf HomeAssistent gewechselt bin 😊

**Comment by larsxschneider** [comment]
Was meinst Du mit "raus kriege"? Willst Du pushover deaktivieren?

**Comment by JHPWBN** [comment]
Genau deaktivieren ist das richtige Wort in diesem Falle Sent from my iPhoneOn 22. Sep 2022, at 19:24, Lars Schneider ***@***.***> wrote:﻿
Was meinst Du mit "raus kriege"? Willst Du pushover deaktivieren?

**Comment by larsxschneider** [comment]
Hmm. Leider kann man das mit dem aktuellen code nicht deaktivieren. Aber du kannst alle deine zonen in `ignoredzones` packen. Dann wird es nicht aufgerufen und dann ist der pushover user und token egal:

Beispiel:
```
 "pushover": {
        "notificationDelay": 15000,
        "ignoredZones": [
            201,
            202,
            203
        ],
        "user": "egal",
        "token": "auchegal"
 }
```

**Comment by raphb83** [comment]
> @JHPWBN Vielen Dank. Das ist nur eine Warning die Du ignorieren kannst - also aendert nichts an der Funktionalitaet. Ich mache keine Aenderungen mehr an dem Plugin weil ich jetzt von homebridge auf HomeAssistent gewechselt bin 😊

@larsxschneider : Wirklich schade, dass an dem Plugin keine Änderungen mehr vorgenommen werden. Habe das Plugin sehr gerne genutzt und mich sehr geärgert, als dann das Software-Update auf der Secvest kam...
Du schreibst davon, dass du von homebridge auf HomeAssistent gewechselt bist - gibt es da eine Möglichkeit, die Secvest - auch die Scharf/Unscharf-Modi wieder HomeKit-Fähig zu machen?

**Comment by larsxschneider** [comment]
> Habe das Plugin sehr gerne genutzt und mich sehr geärgert, als dann das Software-Update auf der Secvest kam...

@raphb83 Hast Du das neuste Secvest update v.3.01.22 installiert? Funktioniert das plugin mit dem update nicht mehr? Ich frage das weil alle plugins (homebridge, homeassistant, ...) auf die gleiche Weise mit der Secvest kommunizieren. Wenn ein plugin nicht mehr geht, dann gehen alle nicht mehr.

> Du schreibst davon, dass du von homebridge auf HomeAssistent gewechselt bist - gibt es da eine Möglichkeit, die Secvest - auch die Scharf/Unscharf-Modi wieder HomeKit-Fähig zu machen?

Kann man machen - hab ich aber nicht implementiert weil meine Schloesser die Alarmanlage schalten und ich die "angriffsflaeche" fuer die Alarmanlage minimieren will. D.h. Homekit/HomeAssistant etc haben bei mir nur die Funktion den aktuellen stand der Alarmanlage _lesend_ zu erfassen und dann entsprechende Automatisierungen zu fahren.

**Comment by raphb83** [comment]
> > Habe das Plugin sehr gerne genutzt und mich sehr geärgert, als dann das Software-Update auf der Secvest kam...
> 
> @raphb83 Hast Du das neuste Secvest update v.3.01.22 installiert? Funktioniert das plugin mit dem update nicht mehr? Ich frage das weil alle plugins (homebridge, homeassistant, ...) auf die gleiche Weise mit der Secvest kommunizieren. Wenn ein plugin nicht mehr geht, dann gehen alle nicht mehr.

@larsxschneider : Habe das Update v.3.01.21 aktuell drauf. Seitdem das Update drauf ist, bekomme ich keinen Status mehr von den Zonen und kann diese auch nicht mehr schalten. 
> 
> > Du schreibst davon, dass du von homebridge auf HomeAssistent gewechselt bist - gibt es da eine Möglichkeit, die Secvest - auch die Scharf/Unscharf-Modi wieder HomeKit-Fähig zu machen?
> 
> Kann man machen - hab ich aber nicht implementiert weil meine Schloesser die Alarmanlage schalten und ich die "angriffsflaeche" fuer die Alarmanlage minimieren will. D.h. Homekit/HomeAssistant etc haben bei mir nur die Funktion den aktuellen stand der Alarmanlage _lesend_ zu erfassen und dann entsprechende Automatisierungen zu fahren.

Ok - das ist verständlich. Und der Absatz
"_Auch ich fände es super, wenn eine Aktivierung / InternAktiv / Deaktivierung möglich wäre (gerne abschaltbar per config) :-)
Und wo wir gerade bei "wünsch Dir was" sind: Vielleicht könnte man auch einen Schalter dazu erfinden, mit dem man das Polling vorübergehend dann via HomeKit abschalten kann, sodass die Abus app benutzbar ist?_"
aus dem Kommentar [https://github.com/larsxschneider/homebridge-secvest-kit/issues/1#issuecomment-875936841](https://github.com/larsxschneider/homebridge-secvest-kit/issues/1#issuecomment-875936841) kommt wirklich nicht in Frage?

Wie hast du dass denn die Secvest in HomeAssistant integriert?

**Comment by larsxschneider** [comment]
> @larsxschneider : Habe das Update v.3.01.21 aktuell drauf. Seitdem das Update drauf ist, bekomme ich keinen Status mehr von den Zonen und kann diese auch nicht mehr schalten.

Hmm. Ich hab auch 3.01.21 ... und bei mir funzt alles. Siehst Du irgendwelche error logs?

**Comment by miixxii** [comment]
Hi guys,

I see your conversation, so just to add I'm running 3.01.22 and have no issues with the plugin. Also I'm giving a vote to option to arm / disarm the alarm via the plugin ;)

have a good day

**Comment by raphb83** [comment]
> > @larsxschneider : Habe das Update v.3.01.21 aktuell drauf. Seitdem das Update drauf ist, bekomme ich keinen Status mehr von den Zonen und kann diese auch nicht mehr schalten.
> 
> Hmm. Ich hab auch 3.01.21 ... und bei mir funzt alles. Siehst Du irgendwelche error logs?

@larsxschneider: Hallo Lars, ich konnte leider gestern nicht mehr antworten - aber ich konnte schauen, ob ich irgendwelche error logs sehe... Aber ich wurde "enttäuscht"... keine error logs. Ich habe dann, eher um zu schauen ob ich das "Problem" reproduzieren kann, eine zweite HomeBridge auf einem anderen Pi aufgebaut - und siehe da, das "Problem" dass keine Stati in HomeKit sind ist weg... Läuft also wieder wie erwartet. Vermute also, dass es an der HomeBridge selbst gelegen hat. Tut mir leid, dass ich dich eventuell unnötig verrückt gemacht habe

Der Kommentar von @miixxii ist wirklich keine Option für dich?

Wie hast du die Secvest in HomeAssistant integriert? Sprich welche Integration nutzt du? Ich habe keine gefunden - außer vielleicht die REST-Integrationen???

**Comment by JHPWBN** [comment]
Hallo Lars,

ich hoffe Du kannst noch mal unterstützen.
Heute wurde auf meinem Secvest die letzte Firmware installiert.

Nachdem ich die neue Anmeldung hingekriegt habe, funktioniert es doch nicht, das plugin stürzt immer ab.

Du hattest auch mal erwähnt, dass du jetzt auf HomeAssistent gewechselt bist, ich wäre gerne bereit zu wechselm.
Gibt es das für iOS und ein Secvest Modul?
Ich brauchte auch ein Modul für Somfy/Tahoma.

Vielen Dank im Voraus!

Schöne Grüße
Joop

Hier die config und Fehlermeldung für das Homebridge Plugin:

{
    "host": "192.168.178.205",
    "port": 4433,
    "username": „nnnn",
    "password": „xxxxxxxxxx",
    "securityPartitions": [
        1
    ],
    "accessoryPartitions": [
        1
    ],
    "pollingInterval": 1,
    "pushover": {
        "notificationDelay": 150000,
        "ignoredZones": [
            201,
            202,
            203
        ]
    },
    "_bridge": {
        "username": "0E:93:34:4F:CA:EF",
        "port": 58694
    },
    "platform": "SecvestKit"
}

TypeError: Cannot read properties of undefined (reading '201')
    at /usr/local/lib/node_modules/homebridge-secvest-kit/src/platform.ts:136:44
    at Array.map (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-secvest-kit/src/platform.ts:133:16)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[7/19/2023, 11:17:56 PM] [homebridge-secvest-kit] Child bridge process ended
[7/19/2023, 11:17:56 PM] [homebridge-secvest-kit] Process Ended. Code: 1, Signal: null
[7/19/2023, 11:18:03 PM] [homebridge-secvest-kit] Restarting Process...
[7/19/2023, 11:18:03 PM] [homebridge-secvest-kit] Launched child bridge with PID 59868
[7/19/2023, 11:18:03 PM] Registering platform 'homebridge-secvest-kit.SecvestKit'

On 22. Sep 2022, at 21:47, Lars Schneider ***@***.***> wrote:


Hmm. Leider kann man das mit dem aktuellen code nicht deaktivieren. Aber du kannst alle deine zonen in ignoredzones packen. Dann wird es nicht aufgerufen und dann ist der pushover user und token egal:

Beispiel:

 "pushover": {
        "notificationDelay": 15000,
        "ignoredZones": [
            201,
            202,
            203
        ],
        "user": "egal",
        "token": "auchegal"
 }

**Comment by larsxschneider** [comment]
👋 Für HomeAssitant hab ich einen kleines Script geschrieben welches die Secvest ausliest und dann per [MQTT](https://www.home-assistant.io/integrations/mqtt/) die Werte an HomeAssitant uebermittelt. Das klappt sehr gut und ich kann das script teilen.

Das script nutzt die selben Kommandos wie mein Homebridge Plugin. Das heisst mit Deiner neuen Secvest version wird es auch nicht funktionieren und wir muessen erstmal rausbekommen warum.

Deswegen ein paar Fragen:
1. Welche Secvest version nutzt Du genau?
2. Welches Betriebsystem nutzt Du (Windows/Mac/Linux/...) ... wenn ich das weiss dann kann ich dir ein paar Testkommandos geben um den Fehler einzugrenzen.

**Comment by JHPWBN** [comment]
Guten morgen Lars,danke für Deine schnelle Antwort, anbei screenshot von der F/W und H/W Version der Zentrale. Alles lauft bei mir auf iMac.Ich werde jetzt erst mal schauen, dass ich die alte F/W wieder drauf kriege, aber langfristig ist es wahrscheinlich besser auf HomeAssistant umzusteigen wegen support oder würdest du die Homebridge Plugin anpassen?Schöne Grüße und vielen herzlichen Dank!Joop==================P.S. Bitte notieren Sie meine neue Email Adresse: ***@***.*** (statt ***@***.***)==================On 20. Jul 2023, at 08:32, Lars Schneider ***@***.***> wrote:﻿
👋 Für HomeAssitant hab ich einen kleines Script geschrieben welches die Secvest ausliest und dann per MQTT die Werte an HomeAssitant uebermittelt. Das klappt sehr gut und ich kann das script teilen.
Das script nutzt die selben Kommandos wie mein Homebridge Plugin. Das heisst mit Deiner neuen Secvest version wird es auch nicht funktionieren und wir muessen erstmal rausbekommen warum.
Deswegen ein paar Fragen:

Welche Secvest version nutzt Du genau?
Welches Betriebsystem nutzt Du (Windows/Mac/Linux/...) ... wenn ich das weiss dann kann ich dir ein paar Testkommandos geben um den Fehler einzugrenzen.

**Comment by miixxii** [comment]
Hi,

Can I add myself to this discussion? I can help with testing.

Personally I reverted back secvest to firmware: v3.01.22 as latest one seems to me changed way how you authenticate on sec_login.cgi.

basically curl with basic authentication doesn't work anymore.

**Comment by JHPWBN** [comment]
Hi, fine with me, as I am definitely not an expert on all of this. I am happy I got (with Lars’ help) Homebridge going some years ago.
It has been stable since then. I use it in combination with Tahoma for my Window Shutters; Hue for Lightning and Eve for Heating Thermostats so that I can manage all that thru Apple’s HomeKit when Secvest Plugin tells me that it is Activated for Away or if a Window opens.

So I’d be extremely thankful if Lars could adapt the Homebridge plugin.

I can help with the authentication matter:

Indeed Abus changed the access method for Web and Secvest App (access on the Panel from the Box stays the same with the 4 digits).

Old situation for Web/App access:

Name e.g.: miixxii
4 digit Password e.g. 1234 (which is the same as you use on the Panel)

With the upgrade, Abus abandons the Name part and adds a Web Access Password which can be any combination of letters, digits etc.. to make it more secure.

After the update you initially have the following situation:

User Code (used to be Name): 4 digit code: 1234
Password: 4 digit code: 1234

so both are the same!

In the User Menu you can now add a Web Access Password e.g. 98d7sf9sdfs.

If you do then you will login with
User Code: 4 digit User Code: 1234
Password: Web Password: 98d7sf9sdfs

If you don’t:
User Code: 4 digit User Code: 1234
Password: 4 digit User Code: 1234

Hope this helps.

Regards,
Joop

On 20. Jul 2023, at 09:14, miixxii ***@***.***> wrote:


Hi,

Can I add myself to this discussion? I can help with testing.

Personally I reverted back secvest to firmware: v3.01.22 as latest one seems to me changed way how you authenticate on sec_login.cgi.

basically curl with basic authentication doesn't work anymore.

**Comment by JHPWBN** [comment]
Hallo Lars, bei Github sehe ich das Screenshot nicht, also hier noch mal als text:

die Version der Secvest F/W ist v3.01.30 (also die, die z.Z. bei Abus zum Download angeboten wird).
Bei mir lauft alles auf iMac.

Sorry wenn das doppelt gemoppelt ist.

Schöne Grüße
Joop

On 20. Jul 2023, at 08:51, Joop Peters ***@***.***> wrote:

Guten morgen Lars,

danke für Deine schnelle Antwort, anbei screenshot von der F/W und H/W Version der Zentrale. Alles lauft bei mir auf iMac.

Ich werde jetzt erst mal schauen, dass ich die alte F/W wieder drauf kriege, aber langfristig ist es wahrscheinlich besser auf HomeAssistant umzusteigen wegen support oder würdest du die Homebridge Plugin anpassen?

Schöne Grüße und vielen herzlichen Dank!

Joop

<image.png>

==================
P.S. Bitte notieren Sie meine neue Email Adresse: ***@***.*** (statt ***@***.***)
==================

On 20. Jul 2023, at 08:32, Lars Schneider ***@***.***> wrote:

﻿

👋 Für HomeAssitant hab ich einen kleines Script geschrieben welches die Secvest ausliest und dann per MQTT <https://www.home-assistant.io/integrations/mqtt/> die Werte an HomeAssitant uebermittelt. Das klappt sehr gut und ich kann das script teilen.

Das script nutzt die selben Kommandos wie mein Homebridge Plugin. Das heisst mit Deiner neuen Secvest version wird es auch nicht funktionieren und wir muessen erstmal rausbekommen warum.

Deswegen ein paar Fragen:

Welche Secvest version nutzt Du genau?
Welches Betriebsystem nutzt Du (Windows/Mac/Linux/...) ... wenn ich das weiss dann kann ich dir ein paar Testkommandos geben um den Fehler einzugrenzen.

**Comment by JHPWBN** [comment]
Guten morgen Lars,

ich habe es inzwischen geschafft Home Assistant zu installieren (bin ganz stolz auf mich :-)), inklusive HomeKit bridge. Ich muss mich jetzt entscheiden, ob ich die alte F/W v3.01.22 auf dem Secvest wieder installieren lasse oder bei der v3.01.30 bleibe.

Ich mache das davon abhängig ob:
- Du dein Home Assistant script anpassen möchtest (dann hätte ich eine „Test“ Umgebung für dich)
oder 
- nicht (könntest Du mir dann das heutige Script für Home Assistant zukommen lassen).

Über eine kurze Rückmeldung deinerseits würde ich mich freuen.

Vielen Dank im Voraus!

Schöne Grüße
Joop

**Comment by larsxschneider** [comment]
@JHPWBN ich melde mich ASAP. Hast Du Lust auf Zoom/Videotelefonie/Screensharing? Dann koennen wir das problem evtl. schneller loesen. Wenn ja, dann schick mir mal ne email an meinen github nutzernamen at gmail punkt com.

**Comment by JHPWBN** [comment]
Hallo Lars. Mail gestern geschickt.
