### ISSUE TITLE
Bekomme PlugIn nicht ans Laufen

### ISSUE THREAD

**Issue by Birdy2019** [larsxschneider/homebridge-secvest-kit#4]
Hallo Lars,

finde Dein PlugIN total genial....bekomme es nur einfach nicht ans Laufen und bräuchte dringend Deine Hilfe.

Nun alle mir vorliegenden Infos:
- Nutze in Partition 1 nur Fensterkontakte
- Nutze in Partition 4 Glasbruchsensoren (die unterstützt Dein Script nicht, richtig?
- - Zone 201 ist ein Fensterkontakt

Meine Config (daten wurden verfälscht)
**Einstellungen: SecvestKit
×
Host *
192.168…..
Port *
1234
Username *
Test
Password *
123456
Security partitions
1
Accessory partitions
1
Zone Types
Zone type

None
Polling interval in minutes *
1
Pushover Configuration
Notification delay *
15
Ignored zones
3
2
user *
[Tes@test.com](mailto:Tes@test.com)	
token *
den habe ich auch**

Fehlerhinweis
24/03/2022, 07:54:31] TypeError: Cannot read properties of undefined (reading '201')
    at /usr/local/lib/node_modules/homebridge-secvest-kit/src/platform.ts:136:44
    at Array.map (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-secvest-kit/src/platform.ts:133:16)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Hoffe, Du kannst mir helfen.

VG
Jochen

**Comment by larsxschneider** [comment]
👋 Jochen! Schwierig zu sagen was da nicht stimmt. Kannst Du Deine Konfiguration nochmal posten (ohne Secrets natuerlich!). Ich glaube in deinem ersten Post fehlt was.

**Comment by Birdy2019** [comment]
Hallo Lars
Mach ich am WE
Grüße 
Jochen

**Comment by Birdy2019** [comment]
Hallo Lars,

anbei meine Confi

{
    "accessories": [
        {
            "swingMode": "1",
            "temperature_unit": "C",
            "retries": 5,
            "enableHumiditySensor": false,
            "response": 2000,
            "apiroute": "http:/",
            "deadline": 60000,
            "system": "Default",
            "defaultMode": "0",
            "fanName": "Livingroom FAN",
            "name": "Daikin Livingroom",
            "fanMode": "FAN",
            "accessory": "Daikin-Local",
            "disableFan": false,
            "fanPowerMode": "FAN only"
        }
    ],
    "bridge": {
        "name": "Homebridge 3B42",
        "username": "vorhanden",
        "port": bekannt,
        "bind": [
            "eth0"
        ],
        "pin": "158-43-776"
    },
    "disabledPlugins": [
        "homebridge-daikin-local"
    ],
    "platforms": [
        {
            "name": "Config",
            "port": gibt es,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "de",
            "platform": "config"
        },
        {
            "password": "hinterlegt",
            "name": "RademacherHomePilot",
            "did_list": [],
            "scenes_as_switch": "true",
            "did_list_usage": "none",
            "debug": "false",
            "platform": "RademacherHomePilot",
            "password_hashed": "true",
            "url": "http://hat eine url"
        },
        {
            "name": "FritzPlatform",
            "debug": true,
            "warn": true,
            "error": true,
            "extendedError": true,
            "devices": [
                {
                    "active": true,
                    "name": "FritzBox 7590",
                    "host": "kennt man",
                    "port": auch den gibt es,
                    "username": "vorhandent",
                    "password": "sag ich nicht",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "manufacturer": "Fritz Box",
                    "model": "7590",
                    "serialNumber": "Steht hinten drauf",
                    "wifiUnits": 2,
                    "master": true,
                    "readOnly": false,
                    "hide": true,
                    "connection": "dsl",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "switch",
                        "wps": "characteristic"
                    }
                }
            ],
            "presence": [
                {
                    "active": true,
                    "blockTelegram": true,
                    "name": "geheim",
                    "address": "vorhanden",
                    "accType": "occupancy",
                    "ping": false
                },
                {
                    "active": true,
                    "blockTelegram": true,
                    "name": "noch geheimer",
                    "address": "vorhanden",
                    "accType": "occupancy"
                }
            ],
            "smarthome": [
                {
                    "active": false
                }
            ],
            "network": [
                {
                    "active": false
                }
            ],
            "callmonitor": {
                "active": true,
                "group": false,
                "countryPrefix": "+49",
                "cityPrefix": "finde es heraus"
            },
            "options": {
                "polling": {
                    "timer": 15
                }
            },
            "platform": "FritzPlatform"
        },
        {
            "password": "fällt mir nicht mehr ein",
            "username": "welcher war es",
            "platform": "TapoP100",
            "devices": [
                {
                    "name": "AQ-Heizung",
                    "updateInterval": 30,
                    "timeout": 2,
                    "host": "192.",
                    "type": "PowerPlug"
                },
                {
                    "name": "AQ-Filter",
                    "updateInterval": 30,
                    "timeout": 2,
                    "host": "192.",
                    "type": "PowerPlug"
                },
                {
                    "name": "AQ-Skimmer",
                    "updateInterval": 30,
                    "timeout": 2,
                    "host": "192.",
                    "type": "Plug"
                },
                {
                    "name": "AQ-CO2",
                    "updateInterval": 30,
                    "timeout": 2,
                    "host": "192.",
                    "type": "Plug"
                },
                {
                    "name": "AQ-Twinstar",
                    "updateInterval": 30,
                    "timeout": 2,
                    "host": "192.",
                    "type": "Plug"
                },
                {
                    "name": "AQ-Lightscreen",
                    "updateInterval": 30,
                    "timeout": 2,
                    "host": "192.",
                    "type": "Plug"
                }
            ],
            "name": "Aquarium"
        },
        {
            "host": "192......",
            "port": 4433,
            "username": "Testt",
            "password": "12345",
            "securityPartitions": [
                1
            ],
            "accessoryPartitions": [
                1
            ],
            "pollingInterval": 1,
            "pushover": {
                "notificationDelay": 15,
                "user": "angemeldet",
                "token": "streng geheim"
            },
            "platform": "SecvestKit"
        },
        {
            "units": "si",
            "interval": 5,
            "stations": [
                {
                    "nameNow": "My Home is my castle",
                    "service": "openweathermap",
                    "key": "geheim",
                    "locationGeo": [
                        1,11111,
                        1,11111
                    ],
                    "locationCity": "siehe oben",
                    "language": "de",
                    "compatibility": "both",
                    "forecast": [
                        "Today",
                        "Tomorrow",
                        "In 7 days"
                    ],
                    "conditionCategory": "detailed",
                    "now": true,
                    "extraHumidity": false,
                    "hidden": [
                        "Dew Point",
                        "Observation Station",
                        "Observation Time",
                        "Solar Radiation",
                        "Sunrise Time",
                        "Sunset Time"
                    ]
                }
            ],
            "platform": "WeatherPlus"
        }
    ]
}


Fehlermeldung
[10/04/2022, 17:09:49] TypeError: Cannot read properties of undefined (reading '201')
    at /usr/local/lib/node_modules/homebridge-secvest-kit/src/platform.ts:136:44
    at Array.map (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-secvest-kit/src/platform.ts:133:16)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Birdy2019** [comment]
Es läuft jetzt endlich, genial
